apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-app
  labels:
    app: transactions-app
spec:
  selector:
    matchLabels:
      app: transactions-app
  template:
    metadata:
      labels:
        app: transactions-app
    spec:
      containers:
        - name: transactions-container
          image: skoirala/sa-miniproject-transaction-service
          envFrom:
            - secretRef:
                name: common-secrets
            - configMapRef:
                name: common-configmap
            - configMapRef:
                name: transaction-app-config

---
apiVersion: v1
kind: Service
metadata:
  name: tx-svc
spec:
  type: ClusterIP
  selector:
    app: transactions-app
  ports:
    - port: 80
      targetPort: 8080


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tx-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /api/transactions
            backend:
              service:
                name: tx-svc
                port:
                  number: 80


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-app-config
data:
  DATABASE_NAME: TransactionDB
